jpa:
  hibernate:
    ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  logging:
    level:
      root: INFO
      kr.co._29cm.homework: DEBUG
      org.hibernate.orm.jdbc.bind: trace