spring:
  application:
    name: homework

  h2:
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/szs
      username: sa
      password:
    sql:
      init:
        mode: always

  jpa:
    hibernate:
      ddl-auto: validate

  logging:
    level:
      root: INFO
      kr.co._29cm.homework: INFO
